base:
  replicas: 1
  imagePullSecrets:
    - name: acrosdev001-azurecr-io
  image:
    repository: nothing
    tag: nothing
  imagePullPolicy: Always
  service:
    type: ClusterIP
  ingress:
    className: azure-application-gateway
    port: 80
    pathType: ImplementationSpecific
  resources:
    requests:
      cpu: 100m
      memory: 200Mi
    limits:
      cpu: 1000m
      memory: 1Gi

  # Job
  restartPolicy: Never
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  backoffLimit: 0
  parallelism: 1

  # Hook
  hook:
    annotations:
      helm.sh/hook: post-install,post-upgrade
