name: kube-prometheus-stack
version: 0.0.0

dependencies:
  - name: base
    version: 0.1.21
    import-values:
      - child: base
        parent: base
  - name: kube-prometheus-stack
    version: 66.2.1
    repository: https://prometheus-community.github.io/helm-charts
  # - name: prometheus-msteams
  #   repository: https://prometheus-msteams.github.io/prometheus-msteams
  #   version: 1.3.0
  # - name: loki-stack
  #   version: 2.10.3
  #   repository: "https://grafana.github.io/helm-charts"
