---
# Source: prometheus-stack/charts/argo/templates/applications.inject.yaml
#
---
# Source: prometheus-stack/templates/main.yaml
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: "monitoring"
  namespace: "argo-cd"
spec:
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  destinations:
    - name: "in-cluster"
      namespace: "argo-cd"
    - name: "in-cluster"
      namespace: "monitoring"
  sourceRepos:
    - '*'
---
# Source: prometheus-stack/templates/main.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: "prometheus-stack"
  namespace: "argo-cd"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: "monitoring"
  source:
    repoURL: "https://github.com/ganeshkr-54/shiptracks_ganesh.git"
    targetRevision: "main"
    path: "helm/monitoring/prometheus"
    helm:
      version: v3
      releaseName: "prometheus-stack"
      valueFiles:
        - values.yaml
  destination:
    name: "in-cluster"
    namespace: "monitoring"
  syncPolicy:
    automated:
      allowEmpty: false
      prune: true
      selfHeal: true
    retry:
      backoff:
        duration: 10s
        factor: 2
      limit: 5
#
#
#
#
#
#
